name: Build Windows EXE (AgendaRadicador)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-freeze.txt', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (prefer freeze)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements-freeze.txt") {
            pip install -r requirements-freeze.txt
          } else {
            pip install -r requirements.txt
          }
          pip install pyinstaller
          python -V
          pip freeze

      - name: Build EXE (debug logs)
        run: |
          pyinstaller --log-level DEBUG --clean build.spec

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: AgendaRadicador-exe
          path: dist/AgendaRadicador.exe
